#Beanstalk deployment 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: beanstalk-deployment
  namespace: default
  labels:
    app: beanstalk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beanstalk
  template:
    metadata:
      labels:
        app: beanstalk
    spec:
      containers:
      - name: beanstalk
        image: schickling/beanstalkd:latest
        ports:
        - containerPort: 11300
---
#Beanstalk Service
kind: Service
apiVersion: v1
metadata:
  name: beanstalk 
spec:
  selector:
    app: beanstalk
  ports:
  - protocol: TCP
    targetPort: 11300
    port: 11300 
  type: LoadBalancer
---



#WorkerB
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: workerb-deployment
#  labels:
#    app: workerb 
#spec:
#  replicas: 2
#  selector:
#    matchLabels:
#      app: workerb 
#  template:
#    metadata:
#      labels:
#        app: workerb
#    spec:
#      containers:
#      - name: workerb
#        image: dgrocki/workerb:latest
#        volumeMounts:
#        - name: wb-vol
#          mountPath: "/mnt"
#      volumes:
#      - name: wb-vol 
#        persistentVolumeClaim:
#          claimName: shared-memory1
#
#---
#WorkManager and WorkerA
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workers
  labels:
    app: workmanager
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workmanager
  template:
    metadata:
      labels:
        app: workmanager
    spec:
      containers:
      - name: workmanager
        image: dgrocki/workmanager:latest
        volumeMounts:
        - name: wm-vol
          mountPath: "/mnt"
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name


      - name: workera1
        image: dgrocki/workera:latest
        volumeMounts:
        - name: wm-vol
          mountPath: "/mnt"
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
      - name: workera2
        image: dgrocki/workera:latest
        volumeMounts:
        - name: wm-vol
          mountPath: "/mnt"
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name



      - name: workerb1
        image: dgrocki/workerb:latest
        volumeMounts:
        - name: wm-vol
          mountPath: "/mnt"
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
      - name: workerb2
        image: dgrocki/workerb:latest
        volumeMounts:
        - name: wm-vol
          mountPath: "/mnt"
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
      volumes:
      - name: wm-vol 
        persistentVolumeClaim:
          claimName: shared-memory1
#---
#kind: Service
#apiVersion: v1
#metadata:
#  name: workmanager 
#spec:
#  selector:
#    app: workmanager 
#  ports:
#  - protocol: TCP
#    port: 8080
#  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-input
  labels:
    app: py 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: py 
  template:
    metadata:
      labels:
        app: py 
    spec:
      containers:
      - name: py
        image: dgrocki/beanstalk-input:latest
        command:
        - /bin/sh
        - "-c"
        - "sleep 60m"

