apiVersion: v1
kind: Service
metadata:
  annotations:
    com.basho.riak.cluster.name: riak-kv
    kompose.cmd: kompose convert
    kompose.version: 1.7.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: member
  name: member
spec:
  ports:
  - name: "8087"
    port: 8087
    targetPort: 8087
  - name: "8098"
    port: 8098
    targetPort: 8098
  selector:
    io.kompose.service: member
status:
  loadBalancer: {}
