apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    com.basho.riak.cluster.name: riak-kv
    kompose.cmd: kompose convert
    kompose.version: 1.7.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: coordinator
  name: coordinator
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: coordinator
    spec:
      containers:
      - env:
        - name: CLUSTER_NAME
          value: riakkv
        image: basho/riak-kv
        name: coordinator
        ports:
        - containerPort: 8087
        - containerPort: 8098
        resources: {}
      restartPolicy: Always
status: {}
